#common configuration shared between all applications
configserver:
    name: Docker Registry
    status: Connected to the Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production

eureka:
    client:
        serviceUrl:
            defaultZone: http://admin:admin@registry:8761/eureka/
